# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_test', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
