# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_test', '0003_answer_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
