# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('error_test', '0004_auto_20170213_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='error_test.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='is_valid',
        ),
    ]
